### PR TITLE
Upgrade to OCamlformat 0.27.0

### PR DESCRIPTION
**Pull request by Julow**
The aim of this preview is to gather feedback.

Changelog can be found here: https://github.com/ocaml-ppx/ocamlformat/blob/main/CHANGES.md

### CODE REVIEW

**Comment by voodoos** [comment]
It looks like previously unformatted files are formatted. Is the due to the way you run the preview ?

**Comment by Julow** [comment]
I do `dune build @fmt --auto-promote` using dune 3.15.0 and I see these files being reformatted. Am I missing something ?

**Comment by voodoos** [comment]
Ah I see. It's an issue with Dune (or our config) that rebuilds the parser unexpectedly. Since your installed version of Menhir is not the same as the one the committed files are, there is a diff (which is unrelated to ocamlformat). We can simply ignore it for the purpose of the preview.

**Comment by voodoos** [comment]
Done directly on main, thanks Jules !

**Pull request closed without merging**
