### PR TITLE
Support for OCaml 4.10

### PR DESCRIPTION
**Pull request by trefis**
- `-short-paths` is working
- the only output in `tests/` is present both with and without `-short-paths` and looks like an improvement to me.

@let-def can you skim over this and make sure there's no "FIXME" or anything of the sort left?

### CODE REVIEW

**Comment by let-def** [comment]
Looking at it!

**Comment by let-def** [comment]
I updated opam constraints to reenable CI.

**Comment by trefis** [comment]
Some tests are broken on "old" versions of OCaml, but these tests were added recently, and are already broken on master.
So I believe this PR is good to squash & merge :)

**Comment by let-def** [comment]
Wunderbar! :fireworks:

**Pull request merged**
