### PR TITLE
Fix build against latest sturgeon

### PR DESCRIPTION
**Pull request by rgrinberg**
and add appropriate opam constraints

Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>

### CODE REVIEW

**Comment by let-def** [comment]
The fix seems right. @rgrinberg: the version of sturgeon released on opam as a wrong install script that copy no files... I made a patch to fix the install procedure. I wonder if I should rerelease 0.4.1 or make a 0.4.2 that is fixed. Do you have any opinion on that?

**Comment by rgrinberg** [comment]
Releasing 0.4.2 would be preferable in my opinion.

**Comment by rgrinberg** [comment]
I think the conflict is necessary as otherwise opam will attempt installation of newer version of merlin along side older versions of sturgeon.

I just changed the conflict to 0.4.2

**Comment by trefis** [comment]
Ping @let-def

**Comment by let-def** [comment]
That's good.

**Comment by Fourchaux** [comment]
In 'merlin.opam' - Line 31 
 
"sturgon" {< "0.4.2"}   should be  "sturgeon" {< "0.4.2"}, no?

**Pull request merged**
