### PR TITLE
Exposes some helper for reducing direct typedtree usage in Lsp

### PR DESCRIPTION
**Pull request by xvw**
Introduction of a module `Merlin_analysis.Typedtree_utils` that can be used in `lsp`. Here, it introduces two function to refactor inferInterface and actionInline.

### CODE REVIEW

**Review by voodoos — COMMENTED** [review]
Thanks Xavier. We have a few other typedtree utils laying around, notably in `Mist_utils`.  I think it would be worth it to organize them all in the same, better named, `Typedtree_utils` module.

Could you also make sure to provide doc comments for every of these utils ?

**Comment by xvw** [comment]
Taking account of your feedbacks @voodoos, thanks!
Two question: 
- I don't think that kind of refactoring deserve a CHANGE entry
- `Misc_utils.Compat` (now `Typedtree_utils.Compat`) seems not used, even in `ocaml-lsp`, should we keep it?

**Comment by voodoos** [comment]
>     * `Misc_utils.Compat` (now `Typedtree_utils.Compat`) seems not used, even in `ocaml-lsp`, should we keep it?

It is not used because we eventually did not make a multi-version release of ocaml-lsp. I would keep it for now, it should be useful when we try again to to it. (No need to keep the Compat module however, you can extract the functions that are inside.)

**Comment by xvw** [comment]
Done!

**Review by voodoos — APPROVED** [review]
Thanks !

**Pull request merged**
