### PR TITLE
Update merlin.opam

### PR DESCRIPTION
**Pull request by Bronsa**

### CODE REVIEW

**Comment by trefis** [comment]
Shouldn't that `version` field just be removed from the opam file?

**Comment by trefis** [comment]
Ping @AltGr .

**Comment by AltGr** [comment]
It's allowed either way: not having it can be more convenient when you have your own version change management mechanics, but having it means it gets picked up by `opam pin` (which will just default to version `dev` if not found)

**Comment by trefis** [comment]
Thanks for your anwser!
If I understand correctly, this will matter for libraries (which might have revdeps), but probably doesn't for merlin (which shouldn't have revdeps).

So I'll close this and remove the version field from our opam file.

Thank you as well @Bronsa!

**Pull request closed without merging**
