### PR TITLE
Further improvements to LSP

### PR DESCRIPTION
**Pull request by andreypopp**

### CODE REVIEW

**Comment by reaysawa** [comment]
@andreypopp I'm trying to use both this branch and the master branch, but one of the requests keeps failing. Here's the log:

```
[Trace - 14:55:27] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/user/reason/test/src/App.re",
        "languageId": "reason",
        "version": 1,
        "text": "let component = ReasonReact.statelessComponent(\"App\");\n\nlet make = children => {\n  ...component,\n  render: self =>\n    <div>\n    ...(children |> Array.of_list |> Array.mapi((child, key) => ReasonReact.element(child.make(~key=key))))\n    </div>,\n};\n"
    }
}


Fatal error: exception End_of_file
[Error  - 14:55:27] [object Object] exited with code: 2
```

It does seem to initialize correctly.

**Comment by andreypopp** [comment]
@reaysawa can you run `ocamlmerlin-lsp` with `OCAMLRUNPARAM=b` environment variable? What editor do you use?

**Comment by reaysawa** [comment]
I'm using https://github.com/neoclide/coc.nvim on Neovim, no extra configuration. Here's the full log with **OCAMLRUNPARAM=b**. Stack trace at the bottom:

```
## versions

vim version: NVIM v0.4.0-161-g8f9fc1f69
node version: v8.12.0
coc.nvim version: 0.0.51
term: xterm-256color
platform: linux

## Error messages

## Output channel: languageserver.ocamlmerlin_lsp
[Trace - 16:02:40] Sending request 'initialize - (0)'.
Params: {
    "processId": 3709,
    "rootPath": "/home/user/reason/test",
    "rootUri": "file:///home/user/reason/test",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {},
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/user/reason/test/src",
            "name": "src"
        }
    ]
}


[Trace - 16:02:40] Received response 'initialize - (0)' in 6ms.
Result: {
    "capabilities": {
        "textDocumentSync": {
            "openClose": true,
            "change": 2,
            "willSave": false,
            "willSaveWaitUntil": false
        },
        "hoverProvider": true,
        "completionProvider": {
            "resolveProvider": false,
            "triggerCharacters": [
                "."
            ]
        },
        "definitionProvider": true,
        "typeDefinitionProvider": true,
        "referencesProvider": false,
        "documentHighlightProvider": false,
        "documentSymbolProvider": true,
        "workspaceSymbolProvider": false,
        "codeActionProvider": false,
        "documentFormattingProvider": false,
        "documentRangeFormattingProvider": false,
        "renameProvider": false,
        "typeCoverageProvider": false,
        "rageProvider": false
    }
}


[Trace - 16:02:40] Sending notification 'initialized'.
Params: {}


[Trace - 16:02:40] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/user/reason/test/src/App.re",
        "languageId": "reason",
        "version": 1,
        "text": "let component = ReasonReact.statelessComponent(\"App\");\n\nlet make = _children => {\n  ...component,\n  render: _self =>\n    <div>\n    {_children}\n    </div>,\n};\n"
    }
}


Fatal error: exception End_of_file
Raised at file "stdlib.ml", line 414, characters 9-26
Called from file "stdlib.ml", line 425, characters 2-25
Called from file "src/extend/extend_main.ml", line 108, characters 17-67
Called from file "src/extend/extend_driver.ml", line 34, characters 8-64
Re-raised at file "src/extend/extend_driver.ml", line 39, characters 4-13
Called from file "src/kernel/mreader_extend.ml", line 52, characters 15-52
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "src/kernel/mreader.ml", line 165, characters 4-78
Called from file "src/kernel/mpipeline.ml", line 103, characters 19-62
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Re-raised at file "src/kernel/mpipeline.ml", line 15, characters 34-49
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Re-raised at file "src/kernel/mpipeline.ml", line 15, characters 34-49
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Re-raised at file "src/kernel/mpipeline.ml", line 15, characters 34-49
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "src/kernel/mpipeline.ml" (inlined), line 78, characters 21-30
Called from file "src/frontend/query_commands.ml", line 64, characters 14-45
Called from file "src/frontend/lsp/ocamlmerlin_lsp.ml", line 142, characters 15-70
Called from file "src/frontend/lsp/ocamlmerlin_lsp.ml", line 454, characters 8-32
Called from file "src/utils/std.ml", line 621, characters 8-12
Re-raised at file "src/utils/std.ml", line 623, characters 30-39
Called from file "src/utils/std.ml", line 621, characters 8-12
Re-raised at file "src/utils/std.ml", line 623, characters 30-39
Called from file "src/lsp/rpc.ml", line 318, characters 21-25
Called from file "src/lsp/rpc.ml", line 361, characters 8-810
Called from file "src/frontend/lsp/ocamlmerlin_lsp.ml", line 480, characters 2-99
Called from file "src/utils/logger.ml", line 123, characters 8-12
Re-raised at file "src/utils/logger.ml", line 125, characters 53-64
Called from file "src/frontend/lsp/ocamlmerlin_lsp.ml", line 499, characters 2-74
[Error  - 16:02:40] [object Object] exited with code: 2
```

**Comment by andreypopp** [comment]
@reaysawa thank you, the issue is likely because `ocamlmerlin-lsp` and `ocamlmerlin-reason` come from different versions of merlin. 

Thank you for testing this!

**Comment by Khady** [comment]
I think you need to install a specific reason-cli version for your OS. You might want to use the 4.02.3+buckle-master switch on opam

**Pull request merged**
