### PR TITLE
Merlin xref

### LINKED ISSUE #735: Please make `merlin-locate/pop-stack` aware of xref
It would be great if `merlin-locate` could integrate with standard emacs [xref](https://www.gnu.org/software/emacs/manual/html_node/emacs/Xref.html) instead of shipping its own solution.

### PR DESCRIPTION
**Pull request by rgrinberg**
Attempt to fix #735

### CODE REVIEW

**Comment by rgrinberg** [comment]
@ejgallego one problem that remains to be solved in this PR is how to handle the symbol at point properly. xref expects the mode to extract the prefix that needs to be completed, while merlin just wants to know the position. Currently I just ignore the `symbol` from xref. But that's probably not right.

**Comment by let-def** [comment]
Thanks, the patch looks good.

Can you add the new elisp file to `EMACS_OBJECTS` in `Makefile`?

**Comment by rgrinberg** [comment]
Did you mean `TARGET_EMACS`? Anyway, I think I updated the makefile and .install file correctly now.

**Comment by trefis** [comment]
Ping @let-def : apparently you've already reviewed this and your request was addressed, do you want to merge this?

**Comment by trefis** [comment]
Actually, this looks fine to me.

**Pull request merged**
