### PR TITLE
Add public_name to merlin libraries (upstream from `ocaml-lsp`)

### PR DESCRIPTION
**Pull request by voodoos**
ping @rgrinberg

### CODE REVIEW

**Review by trefis — APPROVED** [review]

**Comment by rgrinberg** [comment]
How does

**Comment by trefis** [comment]
> I hope there's other motivations for making these libraries public however.

None that I can think of right now, but I'd think LSP is a good enough reason, isn't it?

**Comment by rgrinberg** [comment]
None that I can think of right now, but I'd think LSP is a good enough reason, isn't it?

It’s just as easy for me to maintain a patch separately. I’m also looking into making private vendored libraries usable by adding an appropriate dune feature.

On a related note, it would be quite nice to transition merlin’s libraries to wrapped mode.

**Comment by vch9** [comment]
Hi,

I am glad this PR exist!

I wanted also to voice how this could drastically improve my life. I am vendoring merlin
with the @rgrinberg lsp branch, and it's not that easy to maintain.

The projects I can think of which vendor merlin:
* `ometrics` : https://gitlab.com/nomadic-labs/ometrics
* `coq-of-ocaml`: https://github.com/formal-land/coq-of-ocaml

If there is anything I can do to help you, like testing if these projects still work with this PR, that'd be a pleasure :).

**Comment by voodoos** [comment]
@vch9 yes, this is something we plan to do soon.

I'm closing this specific PR since it has rotten a lot.
Less ambitious changes are being discussed in https://github.com/ocaml/merlin/pull/1448 and https://github.com/ocaml/merlin/pull/1172

**Pull request closed without merging**
