### PR TITLE
Attempt at finding the 'real' capitalization of files on windows

### PR DESCRIPTION
**Pull request by mlasson**
# Description 

When merlin is locating module files, it first tries the capitalized filename (eg. "Module.ml") before the uncapitalized one ("module.ml"). On windows, filenames are case insensitive by default so the first filename matches even if the "real" case is uncapitalized. 

This is not a big problem (because... well it is case insensitive) but it still may confuse text editors that are interacting with merlin (eg. vscode through ocaml-lsp). Even if it is mostly cosmetics (you end up having tabs name that are capitalized when opened first after "Go To Definition", or "recently opened files" appears twice...). 

# What does this PR do ? 

It uses "FindFirstFile" that acts as a kind of "dir/ls" that returns the first filename that matches the inputs query. Here the query is an absolute path without wildcard; so there is at most one match which return as a string option. 

Let's say I have a document "Document.txt" in my home directory, then FindFirstFile("C:\UsErS\MlAsSon\dOcUmEnT.txt") would return "Document.txt".  

This "exact case basename" is then returned to the caml code which compares it with the input basename to check if they are the same (not the same in my example, since "Document.txt" is not "dOcUmEnT.txt"). May be an alternative implementation could have been to to this comparison in the C code. 🤷

Note: this method does not "fix" the case for "whole path" only for the filename (contrary to what has been done 
in commit bf79586fd3b3101f1f7f8e9a34da2f54340b48b0 for macos). 
 
I guess it is related with issues #425 ( and #453) (I guess these "Fixed need test" issues could be closed since it has been tested for 7 years now :)).

### CODE REVIEW

**Comment by nojb** [comment]
For info, I also observed this issue in `emacs`.

**Comment by nojb** [comment]
cc @MisterDA who has worked on previous Windows PRs

**Comment by voodoos** [comment]
Anyone wants to review this ? @MisterDA, @nojb, @let-def ?

**Comment by MisterDA** [comment]
Without testing the Windows specific code, one could also test that Merlin supports well [case-insensitive filesystems on Linux](https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/). Maybe the issue can be reproduced there for non-Windows devs.

**Comment by MisterDA** [comment]
I wonder if it wouldn't be better to open the file anyway, and get the "real" filename from the handle. Also, if we just compare the filenames, there might be problems with Unicode normalization.
https://docs.microsoft.com/en-us/windows/win32/memory/obtaining-a-file-name-from-a-file-handle

**Comment by MisterDA** [comment]
Current master:

```
$ file=src/frontend/ocamlmerlin/ocamlmerlin_server.ml
$ dune exec -- ocamlmerlin single locate -position '95:11' -filename "$file" < "$file"
{"class":"return","value":{"file":"C:\\Users\\antonin\\Tarides\\merlin\\src\\utils\\Std.ml","pos":{"line":52,"col":6}},"notifications":[],"timing":{"clock":47,"cpu":31,"query":0,"pp":0,"reader":0,"ppx":0,"typer":31,"error":0}}
```

With this patch applied:

```
$ file=src/frontend/ocamlmerlin/ocamlmerlin_server.ml
$ dune exec -- ocamlmerlin single locate -position '95:11' -filename "$file" < "$file"
{"class":"return","value":{"file":"C:\\Users\\antonin\\Tarides\\merlin\\src\\utils\\std.ml","pos":{"line":52,"col":6}},"notifications":[],"timing":{"clock":31,"cpu":31,"query":0,"pp":0,"reader":0,"ppx":0,"typer":31,"error":0}}
```

So it seems to be working as expected (the `std.ml` file is lower-case in the returned json).

**Review by nojb — APPROVED** [review]
LGTM

**Comment by nojb** [comment]
> I wonder if it wouldn't be better to open the file anyway, and get the "real" filename from the handle.

Yes, this is another possibility but then you need to parse the returned "real" path to extract the basename. I feel the current approach is simpler.

> Also, if we just compare the filenames, there might be problems with Unicode normalization.

In theory this may also happen already under macOS that also has a special logic in this function, right? But in practice I wonder if it will ever happen that the basename contains non-ASCII characters. (And these would not be valid OCaml module names anyway.)

**Comment by voodoos** [comment]
Thank you @mlasson, could you add a changelog entry and maybe squash the irrelevant commits?

And thanks @MisterDA and @nojb for the review and testing!

**Comment by mlasson** [comment]
Done !

**Pull request closed without merging**
