### PR TITLE
Use open_in_bin not open_in for merlinpp

### PR DESCRIPTION
**Pull request by jonahbeckford**
Fixes https://github.com/ocaml/merlin/issues/1724 thanks to @nojb spotting the problem in https://github.com/ocaml-ppx/ppxlib/pull/465.

### CODE REVIEW

**Comment by jonahbeckford** [comment]
There are also two problematic other uses of `open_in`.

First is https://github.com/ocaml/merlin/blob/master/src/utils/misc.ml#L520-L537

Second is https://github.com/ocaml/merlin/blob/master/src/utils/std.ml#L822-LL839

Both of these are the same and are not used in the Merlin code base. I assume they are helpers for consumers of Merlin (but why is it duplicated?). Regardless, I think those should be changed as well, but that could break Merlin consumers.

**Review by nojb — APPROVED** [review]
LGTM

cc @voodoos who has been approving and merging these PRs lately :)

**Comment by voodoos** [comment]
> There are also two problematic other uses of `open_in`.
> 
> First is https://github.com/ocaml/merlin/blob/master/src/utils/misc.ml#L520-L537
> 
> Second is https://github.com/ocaml/merlin/blob/master/src/utils/std.ml#L822-LL839
> 
> Both of these are the same and are not used in the Merlin code base. I assume they are helpers for consumers of Merlin (but why is it duplicated?). Regardless, I think those should be changed as well, but that could break Merlin consumers.

They might be leftovers since it's not even part of the upstream `Misc` module.

**Review by voodoos — APPROVED** [review]
Looks good to me, thank you @jonahbeckford

**Pull request merged**
