### PR TITLE
Add plugin for deoplete

### PR DESCRIPTION
**Pull request by copy**
Deoplete provides asynchronous completion via neovim's rpc api.

This implements #726.

### CODE REVIEW

**Comment by rlbaker** [comment]
I tried this out locally and was wondering if maybe the regex for plugin is a bit overeager compared to the deoplete regex recommended by [merlin itself](https://github.com/ocaml/merlin/blob/a2facd4bb772ee0261859382964c30e8401866e8/vim/merlin/doc/merlin.txt#L352).

Plugin: `[^\s\'"()]*$`
Merlin: `[^. *\t]\.\w*|\s\w*|#`

I'd love to see this get integrated though, as async vim completion for merlin would be great.

**Comment by copy** [comment]
I released this as a standalone vim plugin: https://github.com/copy/deoplete-ocaml

It would still be nice to have this integrated into merlin, but I'm guessing merlin's authors don't want to deal with the extra maintenance burden.

> I tried this out locally and was wondering if maybe the regex for the plugin is a bit overeager compared to the deoplete regex recommended by merlin itself.
> 
> Plugin: `[^\s\'"()]*$`
> Merlin: `[^. *\t]\.\w*|\s\w*|#`

If you have a test case where this breaks completion, [let me know](https://github.com/copy/deoplete-ocaml/issues/new). I believe merlin completion works even if you provide a longer prefix than necessary, but I haven't tested this thoroughly.

**Comment by ELLIOTTCABLE** [comment]
I'm a little confused about this: Deoplete is explicitly mentioned in `:help merlin`; but the only relevant commit seems to be the one adding that (see #668). Meanwhile, this pull-request was never merged …

So is, or isn't, Deoplete explicitly supported by Merlin right now? If so, what does your plugin add, @copy? Some information about this in the docs would be very welcome.

**Comment by copy** [comment]
@ELLIOTTCABLE By default merlin installs an omnifunc for completion, which works in vim without plugins, but is also picked up by deoplete if no other sources are available ([source](https://github.com/Shougo/deoplete.nvim/blob/master/doc%2Fdeoplete.txt#L615)). However, completion via omnifunc is run on the main thread, so if merlin takes one second to get the completion entries the ui is frozen for that time. See also the related issue: #726.

In order to get proper asynchronous completion I implemented a deoplete plugin. Merlin's authors didn't show much interest (I'm assuming due to the extra maintenance burden of maintaining a plugin they wouldn't use), so I released it as a separate plugin and will maintain it [there](https://github.com/copy/deoplete-ocaml). It uses merlin's api, so it doesn't necessarily need to be integrated into merlin anyway.

**Pull request closed without merging**
