### PR TITLE
Ocamlformat the codebase (again)

### PR DESCRIPTION
**Pull request by voodoos**
I deactivated ocaml-ci so that we can finally format the codebase without breaking the CI..
Options are open for discussion... but not for long :-) @xvw @PizieDust

cc @liam923

### CODE REVIEW

**Review by xvw — APPROVED** [review]
Nice! 
WDYT about merging #1828 before, in order to include the `sherlodoc` sublibrary in the formatting process?

**Comment by voodoos** [comment]
> Nice! WDYT about merging #1828 before, in order to include the `sherlodoc` sublibrary in the formatting process?

I don't see why the order matters, the sherlodoc sublibrary will be formatted either way :-)

**Comment by liam923** [comment]
This looks great to me! I opened a PR against this branch that makes a minor change:
https://github.com/voodoos/merlin/pull/14

Essentially, it allows you to specify a list of files in `src/ocaml` and `src/utils` that should be formatted anyway. This allows us to format files like `src/ocaml/typing/msupport.ml`, which is a Merlin-specific file despite the folder it is located in.

**Comment by PizieDust** [comment]
This looks great :)

**Comment by voodoos** [comment]
> This looks great to me! I opened a PR against this branch that makes a minor change: [voodoos#14](https://github.com/voodoos/merlin/pull/14)
> 
> Essentially, it allows you to specify a list of files in `src/ocaml` and `src/utils` that should be formatted anyway. This allows us to format files like `src/ocaml/typing/msupport.ml`, which is a Merlin-specific file despite the folder it is located in.

Thank you Liam, I cherry-picked your change and added a few more files.

**Pull request merged**
