### PR TITLE
Backport changes from issue #1798

### PR DESCRIPTION
**Pull request by bschommer**
I back ported the changes from issue #1798 since I ran into them recently.

### CODE REVIEW

**Review by xvw — APPROVED** [review]
I am not really familiar with backporting @voodoos but does it require a change entry?

**Comment by bschommer** [comment]
Should I just add the changelog entry and commit it?

**Comment by voodoos** [comment]
Yes please, that would be great.

For your information: we plan to cut a release relatively soon 🙂

**Comment by voodoos** [comment]
Thanks !

**Pull request merged**
