### PR TITLE
[RFC] do not stage parser

### PR DESCRIPTION
**Pull request by trefis**
Or any of the related files.
Instead directly depend on menhir.

In the process:
- fixed a type error in the 4.02 parser
- manually silenced a bunch of "unused value" warnings

### CODE REVIEW

**Comment by trefis** [comment]
@let-def reported that menhir's API is unfortunately not stable, so we cannot afford not to stage.

**Comment by andreypopp** [comment]
Curious what was the motivation for such cnahge.

**Comment by trefis** [comment]
Well, not only do I find the various dune files who currently live under `src/ocaml/preprocess` ugly.
There's also the fact that the rules in there have been silently broken for a while, since dune has moved where it stores its `.cmi` files.

This PR not only simplified the whole thing, it also used the `menhir` rule which is built in dune, and which is kept up to date when `.cmi` files are moved around.

**Comment by trefis** [comment]
Note: I'll try to cook up an alternative solution using the `include_subdirs` stanza.

**Comment by andreypopp** [comment]
Makes sense!

Just that introduction of a new dependency (menhir) made worry a bit — merlin is installed in almost any project I've seen — it's a downside if it would impose a new constraint on menhir.

**Pull request closed without merging**
