### PR TITLE
Add support for `-alert` compiler flag

### LINKED ISSUE #1400: `-alert` not understood by Merlin
It seems Merlin does not understand the `-alert` flag to the compiler.

image

### PR DESCRIPTION
**Pull request by nojb**
Fixes #1400

### CODE REVIEW

**Comment by nojb** [comment]
Friendly ping.

**Review by trefis — APPROVED** [review]
LGTM!

Would you mind adding a test to make sure we don't break this in the future (however unlikely).
It'd be even nicer if you could add the test as a preliminary commit, and updated its output in the later commits. But I understand that might be a bit tedious.

**Comment by nojb** [comment]
> LGTM!
> 
> Would you mind adding a test to make sure we don't break this in the future (however unlikely). It'd be even nicer if you could add the test as a preliminary commit, and updated its output in the later commits. But I understand that might be a bit tedious.

Sure, no problem. I'll do that later today or tomorrow. Thanks for the review!

**Comment by nojb** [comment]
> Would you mind adding a test to make sure we don't break this in the future (however unlikely).
> It'd be even nicer if you could add the test as a preliminary commit, and updated its output in the later commits.

This is now done.

**Pull request merged**
