### PR TITLE
Extension calling error on MacOS

### PR DESCRIPTION
**Pull request by ewenmaclean**
In the current master of merlin, if you run a command such as

`ocamlmerlin single errors -reader reason < test.re`

for a reason file, you get an EOF error. Example output is:

```{"class":"exception","value":"End_of_file\nRaised at file \"pervasives.ml\", line 413, characters 9-26\nCalled from file \"pervasives.ml\", line 424, characters 2-25\nCalled from file \"src/extend/extend_main.ml\", line 108, characters 17-67\nCalled from file \"src/extend/extend_driver.ml\", line 34, characters 8-64\nRe-raised at file \"src/extend/extend_driver.ml\", line 39, characters 4-13\nCalled from file \"src/kernel/mreader_extend.ml\", line 52, characters 15-52\n...```

The reason for this is the change to `create_process` from `open_process` here:

https://github.com/ocaml/merlin/blob/master/src/extend/extend_driver.ml#L26

unfortunately the executable at (in this case) `ocamlmerlin-reason` cannot be found as the environment is empty, except for the necessary `__MERLIN_MASTER_PID` environment variable. What happens on single mode is that the path is made empty by this line:

https://github.com/ocaml/merlin/blob/master/src/frontend/new/new_merlin.ml#L138

In order to remedy this I have reset the `PATH` variable after this command, but I suspect that there is a more principled fix in the external functions provided by the `Os_ipc` module.

### CODE REVIEW

**Comment by ewenmaclean** [comment]
I have tried to run `dune runtest` here (having installed `craml`, `jq` and `realpath`). The version of `realpath` for macOS doesn't like the `-e` argument, but I get the following output:

```No rule found for tests/locate/partial-cmt/a.ml
No rule found for tests/locate/partial-cmt/a.mli
Done: 129/135 (jobs: 2)File "tests/locate/context-detection/mod_constr.t", line 1, characters 0-0:
        diff (internal) (exit 1)
(cd _build/default && /usr/bin/diff -u tests/locate/context-detection/mod_constr.t tests/locate/context-detection/mod_constr.t.corrected)
--- tests/locate/context-detection/mod_constr.t	2018-08-08 15:17:04.000000000 +0100
+++ tests/locate/context-detection/mod_constr.t.corrected	2018-08-08 15:26:49.000000000 +0100
@@ -3,7 +3,7 @@
   {
     "class": "return",
     "value": {
-      "file": "~opam/lib/ocaml/string.ml",
+      "file": "/Users/ewenmaclean/ai/merlin/_opam/lib/ocaml/string.ml",
       "pos": {
         "line": 1,
         "col": 0
Done: 129/135 (jobs: 1)File "tests/locate/non-local/test.t", line 1, characters 0-0:
        diff (internal) (exit 1)
(cd _build/default && /usr/bin/diff -u tests/locate/non-local/test.t tests/locate/non-local/test.t.corrected)
--- tests/locate/non-local/test.t	2018-08-08 15:17:04.000000000 +0100
+++ tests/locate/non-local/test.t.corrected	2018-08-08 15:26:49.000000000 +0100
@@ -3,78 +3,42 @@
   $ $MERLIN single locate -look-for ml -position 1:11 -filename ./b.ml < ./b.ml
   {
     "class": "return",
-    "value": {
-      "file": "tests/locate/non-local/a.ml",
-      "pos": {
-        "line": 1,
-        "col": 4
-      }
-    },
+    "value": "Not in environment 'A.value'",
     "notifications": []
   }
 
   $ $MERLIN single locate -look-for ml -position 5:15 -filename ./b.ml < ./b.ml
   {
     "class": "return",
-    "value": {
-      "file": "tests/locate/non-local/a.ml",
-      "pos": {
-        "line": 1,
-        "col": 4
-      }
-    },
+    "value": "Not in environment 'Indir.value'",
     "notifications": []
   }
 
   $ $MERLIN single locate -look-for ml -position 9:9 -filename ./b.ml < ./b.ml
   {
     "class": "return",
-    "value": {
-      "file": "tests/locate/non-local/a.ml",
-      "pos": {
-        "line": 1,
-        "col": 4
-      }
-    },
+    "value": "Not in environment 'value'",
     "notifications": []
   }
 
   $ $MERLIN single locate -look-for mli -position 1:11 -filename ./b.ml < ./b.ml
   {
     "class": "return",
-    "value": {
-      "file": "tests/locate/non-local/a.mli",
-      "pos": {
-        "line": 3,
-        "col": 0
-      }
-    },
+    "value": "Not in environment 'A.value'",
     "notifications": []
   }
 
   $ $MERLIN single locate -look-for mli -position 5:15 -filename ./b.ml < ./b.ml
   {
     "class": "return",
-    "value": {
-      "file": "tests/locate/non-local/a.mli",
-      "pos": {
-        "line": 3,
-        "col": 0
-      }
-    },
+    "value": "Not in environment 'Indir.value'",
     "notifications": []
   }
 
   $ $MERLIN single locate -look-for mli -position 9:9 -filename ./b.ml < ./b.ml
   {
     "class": "return",
-    "value": {
-      "file": "tests/locate/non-local/a.mli",
-      "pos": {
-        "line": 3,
-        "col": 0
-      }
-    },
+    "value": "Not in environment 'value'",
     "notifications": []
   }

```

**Comment by trefis** [comment]
Hi, sorry for the long delay before getting an answer,

If this is still needed, could you rebase on the latest master?
The issue with `merlin-wrapper-template` has been fixed, as well as various other issues in the testsuite. Which should be a much better starting point to look at this.

**Comment by ewenmaclean** [comment]
thanks - will rebase asap - this is still needed

**Comment by ewenmaclean** [comment]
@trefis - I have rebased and committed the suggested more general fix for this, but I see you already committed my original simpler fix (just preserving PATH) - this is sufficient for us - it is up to you if you want this more general fix (which was suggested on the ocaml slack channel).

**Comment by trefis** [comment]
I guess the long silence speaks for itself.

I'm closing this, thanks @ewenmaclean!

**Pull request closed without merging**
