### PR TITLE
Fix tests in release mode

### PR DESCRIPTION
**Pull request by kit-ty-kate**
This should fix https://github.com/ocaml/opam-repository/pull/18074#issuecomment-771721700
I'm still unsure why it happens but at least it fixes the issue.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
If you're fine with the fix it might need to be cherry-picked to master too

**Comment by trefis** [comment]
I don't think that fix makes sense, at least: I don't understand how it could.
Our tests depend on (and cover) both merlin and dot-merlin-reader.

**Comment by kit-ty-kate** [comment]
but merlin depends on `dot-merlin-reader` already so by transitive dependency it should be fine.

**Comment by trefis** [comment]
That's true at the opam level, but not the dune level.
If we want the tests to run again when `dot-merlin-reader` changes (but `merlin` itself is unchanged) or when it isn't built at all, then we need this.

**Comment by trefis** [comment]
(or I think we do. But perhaps there's some dune magic I'm not aware of)

**Comment by trefis** [comment]
I believe #1259 and #1260 fix this in a more satisfying way.
Thanks though!

**Pull request closed without merging**
