### PR TITLE
Fix windows popup 

### PR DESCRIPTION
**Pull request by jordwalke**
I pieced together many of the different suggestions discussed in [this issue](https://github.com/ocaml/merlin/issues/714).

We need to use the system shell to correctly interpret ppxs, however, when doing so, it makes windows pop up an annoying cmd window on every keystroke. @bryphe's suggestion was to wrap it in a `create_process("cmd.exe", [| theCommand |])`- that got rid of the popup, but it had one problem which we couldn't explain:  The same exact command would not work. I dug into it and it looks like any time you send a command to `cmd.exe` through `create_process`, some quotes get escaped unnecessarily. It doesn't happen with `Sys.command`. I almost gave up hope but at the last minute I thought of a hack: Pass the information through environment variables which will bypass the escaping!

### CODE REVIEW

**Comment by Chimrod** [comment]
I'm just adding a comment to tell you that your solution is working for me. I'm using your patch since about a month without any problem.

I hope this will be merge in the main branch !

**Comment by Chimrod** [comment]
Any news on the patch integration ? The branch requires now some minor modification to work against tag 3.4.2, but the the correction still works and correct a major annoyance (when we use Merlin with autocompletion, the pop ups raise each time we press a key).

**Comment by MisterDA** [comment]
I've tested the PR on Emacs 28+Windows 10, rebased on the 411 branch (currently 4c8f9f8c8b9b9448d4212c262197bee453ee26f9). This PR fixes the problem. Emacs is almost unusable without it when editing a file with ppx. I suggest squashing the PR and hot-fixing it ;)
I think I notice a bit of added latency when typing just after autocompletion with this patch.

**Comment by voodoos** [comment]
Let's close this now that  #1270 has been merged.

**Pull request closed without merging**
