### PR TITLE
Fix change of viewport after MerlinTypeOf in neovim

### PR DESCRIPTION
**Pull request by copy**
In newer versions of neovim, assigning to`vim.current.window.cursor`causes a change in the viewport (#820). In these versions, changing the cursor isn't necessary in the first place, as it was a workaround for older versions of neovim.

This PR also contains an unrelated fix for unnecessary filling of the `:messages` buffer due to an unsilenced `buffer` command.

### CODE REVIEW

**Comment by copy** [comment]
I'm not sure if this still fixes the original issue, because I can't reproduce it anymore. There's is another issue being fixed by this change, which is that the screen position is changed after the window from  `MerlinTypeOf` is closed. Compare the last frame: [master](https://asciinema.org/a/223044) and [this branch](https://asciinema.org/a/223043) (`vim` is aliased to `nvim`).

This fix reverts an old hack from 7efcb2265ed6525bf330666713f70cc83b32ce66 for neovim that doesn't seem to be necessary anymore.

Optimally, the type window shouldn't move the buffer at all if there's enough space, but my vimscript skills aren't good enough to fix this.

cc @trefis

**Comment by trefis** [comment]
> This fix reverts an old hack from 7efcb22 for neovim that doesn't seem to be necessary anymore

Can you expand on that a bit: do you know how long ago this issue was fixed?
Basically, I'm just wondering how likely it is that someone is going to use a version of nvim that still has that bug, and that we'd *break* merlin for him, just to make it visually nicer to other people.

**Comment by copy** [comment]
I tested this a bit more and found that the workaround is actually still necessary in recent versions of neovim. I have pushed an alternative fix that restores the old view after creating the type buffer.

**Comment by trefis** [comment]
The current version looks fine, thanks!

**Pull request merged**
